import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "../lib/StoreProvider";
import MarketDataBar from "./components/MarketDataBar";

const poppins = Poppins({ weight:"400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={poppins.className}>
          <MarketDataBar/>

           {children}
        </body>
       </StoreProvider>
    </html>
  );
}
