import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import StoreProvider from "../lib/StoreProvider";
import MarketDataBar from "./components/MarketDataBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <MarketDataBar/>
          <div>
            <Link href='/'>Home</Link>
            <Link href='/portfolio'>Portfolio</Link>
          </div>
           {children}
        </body>
       </StoreProvider>
    </html>
  );
}
