import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "../lib/StoreProvider";
import MarketDataBar from "./components/MarketDataBar";
import { Themeprovider } from "./Themeprovider";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <StoreProvider>
        <body className={poppins.className}>
          <Themeprovider>
            <MarketDataBar />
            {children}
          </Themeprovider>
        </body>
      </StoreProvider>
    </html>
  );
}
